version: '3'

services:
  #service 1: definition of mongodb database
  mongo-db:
    image: mongo:latest
    container_name: "mongo-db"
#    environment:
#      - MYSQL_ROOT_PASSWORD=admin123
#      - MYSQL_DATABASE=mediscreen-patient
#      - MYSQL_USER=sqluser
#      - MYSQL_PASSWORD=Sql2015
    ports:
      - 27018:27017
    restart: always
  mediscreen-note:
    image: mediscreen-note
    container_name: mediscreen-note
    restart: on-failure
    ports:
      - 8082:8082
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      SPRING_DATA_MONGODB_HOST : mongo-db
    depends_on:
      - mongo-db
